{{- if .Values.additionalLoggingSources.rke.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ .Release.Name }}-rke-aggregator"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-rke-aggregator
  template:
    metadata:
      name: "{{ .Release.Name }}-rke-aggregator"
      namespace: "{{ .Release.Namespace }}"
      labels:
        name: {{ .Release.Name }}-rke-aggregator
    spec:
      containers:
        - name: fluentbit
          image: "{{ template "system_default_registry" . }}{{ .Values.images.fluentbit.repository }}:{{ .Values.images.fluentbit.tag }}"
          volumeMounts:
            - mountPath: /var/lib/rancher/rke/log/
              name: indir
            - mountPath: /var/lib/rancher/logging/
              name: outdir
            - mountPath: /var/lib/docker/containers/
              name: containers
            - mountPath: /tail-db
              name: tail-db
            - mountPath: /fluent-bit/etc/fluent-bit.conf
              name: config
              subPath: fluent-bit.conf
      volumes:
        - name: indir
          hostPath:
            path: /var/lib/rancher/rke/log/
            type: DirectoryOrCreate
        - name: outdir
          hostPath:
            path: /var/lib/rancher/logging/
            type: DirectoryOrCreate
        - name: containers
          hostPath:
            path: /var/lib/docker/containers/
            type: DirectoryOrCreate
        - name: tail-db
          hostPath:
            path: /var/lib/rancher/logging/tail-db/
            type: DirectoryOrCreate
        - name: config
          configMap:
            name: "{{ .Release.Name }}-rke"
      {{- $total_tolerations := concat (.Values.tolerations) (.Values.fluentbit.tolerations) }}
      {{- with $total_tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
